language: node_js
node_js: stable
dist: trusty
sudo: required
addons:
  firefox: latest
  sauce_connect: true
  apt:
    sources:
    - google-chrome
    packages:
    - google-chrome-stable
before_script:
- npm install -g bower web-component-tester
- export PATH=$PWD/node_modules/.bin:$PATH
- bower install
script:
- xvfb-run wct --skip-plugin sauce
- if [ "${TRAVIS_PULL_REQUEST}" = "false" ]; then wct --skip-plugin local; fi
env:
  global:
  - secure: cOyYR21znpC/T/C1qw/scCXJP86wxI9xvJh3E7Zgb7ZeKRlZGM2XIT95+9el4cTtPYVwavSlzy7HlGsSt5ugZtSo1htgk9GobBdznMfH6xj/gcUyllG4r2/UecPd3rugrLJgKcxTd4kNPj2U3MJeBryNfaKJGQ/PP1K+xKjc+2CFFegMID4kK2UBshUV9RER62JnU6iTVCNPiwTRMCkM5lkczaODWXc1XEyNS65tWEcQe+ueN4P9I1LZcIfD+jh5hKOBgLYq4rXUPxPsm4gNn3h/kGmooVqwX9hTYewh3zXDKKlTHoSOfEycCz0vmAZaTW+9lciHHrIc9mxOTItthc7HQgY/QZmfGKKujx740cxnOnv7AYwALEqYyOvWyFmq+Z0ovTXP9v82IpiHdRd7gAcNBXIVqxSrJCtdkfy5RaN2WNRsIZfBKRXL0+ts/u0ehpX1zBJ/OxtLimf8nthWGoUEOW7xSfBw9W79KaNArCWzA3B6801skHhLuJCfCJJmZo4+HyBE049JwzP9Iq+gTksUTDIpOAwfwEC1O4bFaoyjSRnFmJVTGtnjjVgwOI6gRu66bXpKZ3WCwjOxU8C7CBeG1eOd4HK5GK5clTzxyI6VRTBs2AJYk2MOmml4vxbTpQQ89PHHexA5v0HsjQHkng/lFhL1GQV1o2aCLcssB7Y=
  - secure: arhLGFppd+2/gc0Sn56LOmoWIzoiHamapu1ZPwTTF/G6xFvxQLVZL/4ofguFsK8mNpTOGGplSl2ck8DeSFOLTfr4MYu40VC4ZDgGF75jGT9crvcgZP+xoJlLnFoDuajZBBmnji3WzVDVsn3NIebE6RvIBeTdfWNDjDLGJ0GYaTkTsOU7sShzfuMErPzeUsxpTGkxa50qzd+QC34mH5eiQQzvgtLCWNUL87fjWpt1KwlwY/nCGHWzwfq2QZCiE6ZT+Pg3wxI3SLNrWtUymzc06SL0Vyc+LHJQi79/PN/CJCYkV20tRGcYADUgUAwfLZ4SsAvVQDbi3mA+1cb/56M9Fh5rjFAKddRqzX+LDnJqTrMWNEbpADkKwB5ZDIK2XOYtWHtmNT3L7z3yTjW+Ntpvr3I99I129boVNsTavPWpZxpp6wQJ2GYE+VlINRWq9FiaEfFmBw4bMec6k43t5wQgHWGvq7FtoNc6zNC9Sest0Nm90FFXjNdhLxUlXV9kFhkISvOlPbx5tpnqg8qolKBgOQzj0LNI7soxbFeAMYb84j/x1cVNwfmQXboTii+8afLFFd4g0Z3Lftjqy+lExWAYMteP6UIynWLsb3VYoy1CiJTx7G7dPtCi+KE//Mmt815ZR2q5D3Mld1l3zdsx742lt2y6U8rjvmaAX9jpXWOkiYw=
  - secure: WJ6lAnnkyB5QowDn134iWEv0iLXB8M+y4Q0vq+ZgP0In92HkwH2CeNfxGWf6fjfG5IcptcB7W3o67u0+M/jcaTHQuuABIEg03ztdgPJH9txTiAx2huaStRu0bKlqg34frTc9q7dQ1DGtMHhM7nbzutn/VzJ5LyZztGENYQ5IwxyxAM99QCCDBcszH8GkTMyjYCdHT25uFOkbGMt8bs6MqCt5LQeHvx0RjGBioYIJRd2g2iKPYM+nxWgZ2MEZYzG8xA7HWeVvcxnf+6PO3H5igQ/kgHJoz5HEBK0SA1oKeh+GDONpauQZKXZgnNr1JlavfFjKwzN3Ab/AjJLLYK5KOwIMq5y5Nw+y2ZzCDqDAtaO4X2fkzO7w9UTDNJYD9T1T5U3MNcq5wyCY128CPtFCRTGmsWStSbig5+yxhehqg+4TkB2VT0BvgxmrvTLCB6+298HSfAHxTcALAfYAccKhgzZXgyvtvzPDKWe+eeRYYZi5z+qQUNaSACHnUTMj3CqZ7pr7yPKN5WTVMwNuABdK9DLWT3N4hJLw9oMr0S0peba/ZKxVXNCSlOofG7Iuu6VuWQAM3Y6RAS5dmK0geTH/Z9FIAxLAfdUlTZu/8FKNZ6EL4pCo3/dpDCtz7YPrwxB19WUh52qjkzRdAjmFT29u3OcjujWYbJVl0WliYP6l0TE=
